version: '3.8'

services:
  ffc-grants-stubs:
    build:
      context: .
      target: production
    image: ffc-grants-stubs
    container_name: ffc-grants-stubs
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      APPLICATION_TOPIC_ADDRESS: ${APPLICATION_TOPIC_ADDRESS:-notset}
      APPLICATION_SUBSCRIPTION_ADDRESS: ${APPLICATION_SUBSCRIPTION_ADDRESS:-notset}
      CONTACT_TOPIC_ADDRESS: ${CONTACT_TOPIC_ADDRESS:-notset}
      CONTACT_SUBSCRIPTION_ADDRESS: ${CONTACT_SUBSCRIPTION_ADDRESS:-notset}
