version: '3.8'

services:
  ffc-grants-stubs:
    build:
      context: .
      target: production
    image: ffc-grants-stubs
    container_name: ffc-grants-stubs
    environment:
      ELIGIBILITY_QUEUE_ADDRESS: ffc-grants-eligibility-${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
