version: '3.8'

services:
  ffc-grants-stubs:
    build:
      context: .
      target: production
    image: ffc-grants-stubs
    container_name: ffc-grants-stubs
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      APPLICATION_TOPIC_ADDRESS: ffc-grants-application-${MESSAGE_QUEUE_SUFFIX}
      APPLICATION_TOPIC_SUBSCRIPTION: ffc-grants-formatter-${MESSAGE_QUEUE_SUFFIX}
      CONTACT_TOPIC_ADDRESS: ffc-grants-contact-${MESSAGE_QUEUE_SUFFIX}
      CONTACT_TOPIC_SUBSCRIPTION: ffc-grants-customer-${MESSAGE_QUEUE_SUFFIX}
